version: "3.2"
services:
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"

  redis:
    image: redis:latest

  web: &app
    build: .
    volumes:
      - .:/app
      - cache:/app/.cache:delegated
    command: sh -c 'wait-for-it db:5432 redis:6379 -- honcho start -f Procfile.dev' web
    environment:
      # pass those two into the environment
      # but also response the .env file for the rest
      FLASK_APP: jazzband/app.py
      FLASK_DEBUG: 1
    env_file:
      - .env
    ports:
      - "5000:5000"
    links:
      - db
      - redis

  # scheduler:
  #   <<: *app
  #   command: honcho start -f Procfile.dev scheduler

  worker:
    <<: *app
    command: sh -c 'wait-for-it db:5432 redis:6379 -- honcho start -f Procfile.dev worker'
    ports: []

volumes:
  cache:
